from typing import Protocol, List, Type, Tuple, Dict, Optional, Union, Sequence
from daft import DataFrame
from lancedb.pydantic import LanceModel

class Component(LanceModel):
    pass

ArchetypeSignature = Tuple[Type[Component], ...]

class iProcessor(Protocol):
    priority: int
    components: Tuple[Type[Component], ...]
    def process(self, df: DataFrame) -> DataFrame | None: ...

class iStore(Protocol):
    def add_entity(self, components: List[Component], step: int) -> int: ...
    def remove_entity(self, entity_id: int, step: int) -> None: ...
    def get_archetype_for_entity(self, entity_id: int, *component_types: Type[Component]) -> DataFrame: ...
    def get_matching_archetypes(self, *component_types: Type[Component]) -> Dict[str, DataFrame]: ...
    def append(self, table_name: str, df: DataFrame) -> None: ...

class iQuerier(Protocol):
    def get_archetypes(self, step: int) -> List[Tuple[ArchetypeSignature, DataFrame]]: ...
    def archetype_for_entity(self,entity_id: int, component_types: Sequence[Type[Component]], step: List[int]) -> DataFrame: ...

class iUpdater(Protocol):
    def update(self, archetypes: Dict[str, DataFrame]): ...

class iSystem(Protocol):
    def add_processor(self, processor: iProcessor) -> None: ...
    def remove_processor(self, processor: iProcessor) -> None: ...
    def execute(self, querier: iQuerier, step: int, dt: float) -> Dict[str, DataFrame]: ...

class iWorld(Protocol):
    def __init__(self, store: iStore, querier: iQuerier, updater: iUpdater, system: iSystem): ...
    def step(self, dt: float): ...
    def spawn(self, components: List[Component], step: Optional[int] = None) -> int: ...
    def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    def remove(self, entity_id: int, comp_type: Type[Component]) -> None: ...

###################
# Async Interfaces
###################
class iAsyncQuerier(Protocol):
    async def query(self, *component_types: Type[Component], step: int, entities: Optional[Union[int, List[int]]] = None) -> DataFrame: ...

class iAsyncUpdater(Protocol):
    async def update(self, archetypes: Dict[str, DataFrame]): ...

class iAsyncWorld(Protocol):
    def step(self, dt: float): ...
    async def spawn(self, components: List[Component], step: Optional[int] = None) -> int: ...
    async def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    async def remove(self, entity_id: int, comp_type: Type[Component]) -> None: ...