# Copyright 2025 Vangelis Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Protocol, List, Type, Tuple, Dict, Optional, Any
from daft import DataFrame
import pyarrow as pa
from archetype.core import Component

class iComponent(Protocol):
    def get_prefix(self) -> str: ...
    def to_pyarrow_schema(self) -> pa.Schema: ...
    def get_prefixed_schema(self) -> pa.Schema: ...
class iArchetype(Protocol):
    def sig_from_components(self, components: List[iComponent]) -> ArchetypeSignature: ...

class iProcessor(Protocol):
    components: Tuple[Type[iComponent], ...] = None
    priority: int = 0
    def process(self, df: DataFrame, *args, **kwargs) -> DataFrame: ...

class iStore(Protocol):
    def add_entity(self, components: List[Component], step: int, world_id: str, run_id: str ) -> int: ...
    def remove_entity(self, entity_id: int, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> None: ...
    def get_archetype_for_entity(self, entity_id: int, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> DataFrame: ...
    def get_archetype(self, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> Tuple[ArchetypeSignature, DataFrame]: ...
    def append(self, sig: ArchetypeSignature, df: DataFrame, step: int, world_id: str, run_id: str) -> None: ...
    def materialize_spawns(self, spawn_cache: Dict[ArchetypeSignature, List[Dict[str, Any]]], world_id: str, run_id: str) -> None: ...

class iQuerier(Protocol):
    def get_archetype(self, sig: ArchetypeSignature, current_step: int, world_id: str, run_id: str) -> Tuple[ArchetypeSignature, DataFrame]: ...
    def get_archetype_for_entity(self, entity_id: int, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> DataFrame: ...

class iUpdater(Protocol):
    def update(self, df: DataFrame, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> None: ...
    def materialize_spawns(self, spawn_cache: Dict[ArchetypeSignature, List[Dict[str, Any]]], world_id: str, run_id: str) -> None: ...

class iSystem(Protocol):
    def add_processor(self, processor: iProcessor) -> None: ...
    def remove_processor(self, processor: iProcessor) -> None: ...
    def execute(self, df: DataFrame, sig: ArchetypeSignature, *args, **kwargs) -> DataFrame: ...

class iWorld(Protocol):
    def __init__(self, store: iStore, querier: iQuerier, updater: iUpdater, system: iSystem): ...
    def step(self, dt: float): ...
    def spawn(self, components: List[Component], step: Optional[int] = None) -> int: ...
    def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    def remove(self, entity_id: int, comp_type: Type[Component]) -> None: ...
