# Copyright 2025 Vangelis Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Protocol, List, Type, Tuple, Optional
from daft import DataFrame
from .component import Component
from .config import RunConfig


ArchetypeSignature = Tuple[Type['Component'], ...]

#---------------------------------------
# Synchronous interfaces
# --------------------------------------
class iProcessor(Protocol):
    components: Tuple[Type['Component'], ...] = None
    priority: int = 0
    def process(self, df: DataFrame, *args, **kwargs) -> DataFrame: ...

class iSystem(Protocol):
    def add_processor(self, processor: iProcessor) -> None: ...
    def remove_processor(self, processor: iProcessor) -> None: ...
    def execute(self, df: DataFrame, sig: ArchetypeSignature, *args, **kwargs) -> DataFrame: ...
class iStore(Protocol):
    def get_archetype_df(self, sig: ArchetypeSignature) -> DataFrame: ...
    def append(self, sig: ArchetypeSignature, df: DataFrame, tick: int, world_id: str, run_id: str) -> None: ...
    def shutdown(self) -> None: ...

class iQueryManager(Protocol):
    def get_archetype(self, sig: ArchetypeSignature, world_id: str, run_id: str) -> DataFrame: ...
    def query_archetype(self, sig: ArchetypeSignature, world_id: str, run_id: str, ticks: Optional[List[int]] = None, entity_ids: Optional[List[int]] = None, components: Optional[List[Component]] = None) -> DataFrame: ...

class iUpdateManager(Protocol):
    def update(self, df: DataFrame, sig: ArchetypeSignature, tick: int, world_id: str, run_id: str) -> None: ...

class iWorld(Protocol):
    def run(self, run_config: RunConfig, **input_kwargs) -> None: ...
    def step(self, run_config: RunConfig, **input_kwargs) -> None: ...
    def _run_archetype(self, sig: ArchetypeSignature, **input_kwargs) -> Tuple[DataFrame, ArchetypeSignature]: ...
    def materialize_mutations(self, df: DataFrame, sig: ArchetypeSignature) -> DataFrame: ...
    @property
    def active_signatures(self) -> Tuple[Type[Component], ...]: ...
    def create_entity(self, components: List[Component]) -> int: ...
    def remove_entity(self, entity_id: int) -> None: ...
    def add_components(self, entity_id: int, components: List[Component]) -> None: ...
    def remove_components(self, entity_id: int, component_types: List[Type[Component]]) -> None: ...
    def add_processor(self, proc: iProcessor) -> None: ...
    def remove_processor(self, proc_type: Type[iProcessor]) -> None: ...
    def query_archetype(self, sig: ArchetypeSignature, ticks: Optional[List[int]] = None, entity_ids: Optional[List[int]] = None, components: Optional[List[Component]] = None, run_config: Optional[RunConfig] = None) -> DataFrame: ...
    def get_components(self, components: List[Component], entity_ids: Optional[List[int]] = None) -> DataFrame: ...
    def execute(self, df: DataFrame, sig: ArchetypeSignature, **input_kwargs) -> DataFrame: ...
    def update(self, df: DataFrame, sig: ArchetypeSignature, tick: int | None = None) -> None: ...


#---------------------------------------
# Asynchronous interfaces
# --------------------------------------
class iAsyncProcessor(Protocol):
    components: Tuple[Type['Component'], ...] = None
    priority: int = 0
    async def process(self, df: DataFrame, **input_kwargs) -> DataFrame: ...

class iAsyncSystem(Protocol):
    async def add_processor(self, proc: iAsyncProcessor) -> None: ...
    async def remove_processor(self, proc_type: Type[iAsyncProcessor]) -> None: ...
    async def execute(self, df: DataFrame, sig: ArchetypeSignature, **input_kwargs) -> DataFrame: ...

class iAsyncStore(Protocol):
    async def get_archetype_df(self, sig: ArchetypeSignature, world_id: str, run_id: str) -> DataFrame: ...
    async def append(self, sig: ArchetypeSignature, df: DataFrame) -> None: ...
    async def shutdown(self) -> None: ...
class iAsyncQueryManager(Protocol):
    async def get_archetype(self, sig: ArchetypeSignature, world_id: str, run_id: str) -> DataFrame: ...
    async def query_archetype(self, sig: ArchetypeSignature, world_id: str, run_id: str, ticks: Optional[List[int]] = None, entity_ids: Optional[List[int]] = None, components: Optional[List[Component]] = None) -> DataFrame: ...

class iAsyncUpdateManager(Protocol):
    async def update(self, df: DataFrame, sig: ArchetypeSignature, tick: int, world_id: str, run_id: str) -> DataFrame: ...
class iAsyncWorld(Protocol):
    async def run(self, run_config: RunConfig, **input_kwargs) -> None: ...
    async def step(self, run_config: RunConfig, **input_kwargs) -> None: ...
    async def _run_archetype(self, sig: ArchetypeSignature, **input_kwargs) -> Tuple[DataFrame, ArchetypeSignature]: ...
    def materialize_mutations(self, df: DataFrame, sig: ArchetypeSignature) -> DataFrame: ...
    @property
    def active_signatures(self) -> Tuple[Type[Component], ...]: ...
    async def create_entity(self, components: List[Component]) -> int: ...
    async def remove_entity(self, entity_id: int) -> None: ...
    async def add_components(self, entity_id: int, components: List[Component]) -> None: ...
    async def remove_components(self, entity_id: int, component_types: List[Type[Component]]) -> None: ...
    async def add_processor(self, proc: iAsyncProcessor) -> None: ...
    async def remove_processor(self, proc_type: Type[iAsyncProcessor]) -> None: ...
    async def query_archetype(self, sig: ArchetypeSignature, ticks: Optional[List[int]] = None, entity_ids: Optional[List[int]] = None, components: Optional[List[Component]] = None, run_config: Optional[RunConfig] = None) -> DataFrame: ...
    async def get_components(self, components: List[Component], entity_ids: Optional[List[int]] = None) -> DataFrame: ...
    async def execute(self, df: DataFrame, sig: ArchetypeSignature, **input_kwargs) -> DataFrame: ...
    async def update(self, df: DataFrame, sig: ArchetypeSignature, tick: int | None = None) -> None: ...



