[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "getdaft>=0.4.8",
    "lancedb>=0.21.2",
    "numpy>=2.2.4",
    "pyglet>=2.1.3",
    "pyiceberg>=0.9.0",
    "ray>=2.44.1",
]
