[project]
name = "archetype"
version = "0.1.0"
description = "AI Native Simulation Engine leveraging Daft, LanceDB, and Ray for distributed scalability."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "daft[lance,iceberg,sql,unity]>=0.5.18",
    "pyarrow>=16.0.0",
    "lancedb>=0.22.0",
    "pyiceberg[daft,sql-sqlite]>=0.9.1",
    "unitycatalog-client>=0.3.0",
    "uuid-utils>=0.11.0",
    "igraph",
    "psutil",
    "viztracer>=1.0.4",
    "ruff>=0.4",
    "ipykernel",
]

[project.optional-dependencies]
ray        = ["ray[default]>=2.47", "fastapi>=0.110", "uvicorn[standard]>=0.29"]
llm        = ["openai"]
inference  = ["ray[serve,llm]>=2.47", "vllm>=0.7.2", "huggingface-hub>=0.26", "transformers>=4.49", "accelerate>=0.29", "datasets>=3.6"]
benchmark  = ["esper>=2.45", ]
dev        = [
    "pytest>=8.3", "pytest-asyncio>=0.26", "pytest-cov>=5.0",
    "ruff>=0.4", "matplotlib>=3.9", "viztracer>=1.0.4"
]


[tool.pytest.ini_options]
pythonpath = [
    "src"
]
asyncio_default_fixture_loop_scope = "function"
