import asyncio
from typing import List, Type, Optional, Any, Dict

import daft
from daft import col, DataFrame
import pandas as pd
import networkx as nx
import ulid

from archetype.core.interfaces import Component, iWorld
from .graph_store import GraphStore
from archetype.core.querier import AsyncQueryManager 
from .graph_system import AsyncGraphSystem
from .components import NodeID, LLMAgentState, GraphNodeComponent
from .llm_agent_processor import LLMAgentProcessor

# --- Conceptual World for Graph-Based Multi-Agent Systems ---
class GraphWorld(iWorld):
    """ 
    Orchestrates a graph-based multi-agent simulation.
    Uses GraphStore, AsyncQueryManager, and AsyncGraphSystems.
    Supports streaming execution, LLM agent processing, and graph dynamics.
    """
    def __init__(self, 
                 store_uri: str,
                 simulation_id: Optional[str] = None,
                 run_id: Optional[str] = None,
                 entity_namespace: str = "archetypes",
                 edge_namespace: str = "graph_edges",
                 ray_serve_endpoint_url: Optional[str] = "http://localhost:8000", # Default for local Ray Serve
                 max_concurrent_store_requests: int = 10):
        
        self.simulation_id = simulation_id or f"sim_{ulid.new()}"
        self.run_id = run_id or f"run_{ulid.new()}"

        self.store = GraphStore(
            uri=store_uri, 
            simulation=self.simulation_id, 
            run=self.run_id,
            entity_namespace=entity_namespace,
            edge_namespace=edge_namespace,
            max_concurrent_requests=max_concurrent_store_requests
        )
        self.querier = AsyncQueryManager(store=self.store)
        self.systems: List[AsyncGraphSystem] = []
        self._current_step = 0
        self._is_running = False
        self.ray_serve_endpoint_url = ray_serve_endpoint_url
        
        # Example: Auto-add a default agent system if an endpoint is provided
        if self.ray_serve_endpoint_url:
            agent_system = AsyncGraphSystem(max_concurrent_processors=5) # Concurrency for this system
            # The LLMAgentProcessor would be instantiated with the endpoint URL
            agent_system.add_processor(LLMAgentProcessor(ray_serve_endpoint_url=self.ray_serve_endpoint_url))
            self.add_system(agent_system)

    def add_system(self, system: AsyncGraphSystem) -> None:
        self.systems.append(system)

    def remove_system(self, system_type: Type[AsyncGraphSystem]) -> None:
        self.systems = [s for s in self.systems if not isinstance(s, system_type)]

    # --- Entity and Edge Management --- 
    async def async_add_entity(self, components: List[Component], entity_id: Optional[NodeID] = None, step: Optional[int] = None) -> NodeID:
        actual_step = step if step is not None else (self._current_step if self._is_running else 0)
        # The store's add_entity is currently synchronous and returns int. 
        # We might need to align if NodeID can be str from the start or if store handles conversion.
        # For now, let's assume entity_id generation is handled by the store or passed in.
        # If entity_id is provided, it implies an update or specific ID assignment (complex).
        # The core AsyncArchetypeStore.async_add_entity returns an int.
        if entity_id is not None:
            # This branch implies more complex logic for presetting IDs, which the store might not support directly for new entities.
            # For now, let this be conceptual that an ID *can* be influenced.
            # The current store.async_add_entity will generate its own ID.
            # To truly use a predefined NodeID (if string), store would need modification.
            print(f"Warning: entity_id hint ({entity_id}) provided, but store will generate its own int ID.")
        
        new_entity_id_int = await self.store.async_add_entity(components, step=actual_step)
        return new_entity_id_int # Return the int ID generated by the store

    async def async_add_edge(
        self, 
        source_id: NodeID, 
        target_id: NodeID, 
        relation_type: str,
        edge_components: List[Component], # Expecting List[GraphEdgeComponent]
        step: Optional[int] = None
    ) -> str: # Returns the edge_id
        actual_step = step if step is not None else (self._current_step if self._is_running else 0)
        return await self.store.async_add_edge(source_id, target_id, relation_type, edge_components, actual_step)

    # --- Simulation Loop --- 
    async def run_step_async(self, dt: float = 1.0) -> None:
        """Executes one step of the simulation asynchronously."""
        self._is_running = True
        current_processing_step = self._current_step
        print(f"--- World Step {current_processing_step} Starting --- DT: {dt} ---")
        
        await self.store.materialize_spawns() # Entities & Edges from previous step or setup

        system_tasks = []
        for system_idx, system in enumerate(self.systems):
            print(f"  Executing System {system_idx}...")
            task = asyncio.create_task(system.execute_streaming(
                querier=self.querier,
                store=self.store, 
                step=current_processing_step,
                dt=dt
            ))
            system_tasks.append(task)
        
        if system_tasks:
            results = await asyncio.gather(*system_tasks, return_exceptions=True)
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    print(f"  Error in System {i}: {result}")

        # Materialize changes made by systems in *this* step
        # Ensures all DataFrame appends are committed before next step begins.
        print(f"  Materializing all changes for step {current_processing_step}...")
        await self.store.materialize_spawns() 

        self._current_step += 1
        self._is_running = False
        print(f"--- World Step {current_processing_step} Complete --- Next step will be {self._current_step} ---")

    async def run_simulation_async(self, num_steps: int, dt: float = 1.0) -> None:
        print(f"Starting simulation for {num_steps} steps with DT={dt}.")
        for i in range(num_steps):
            await self.run_step_async(dt=dt)
            # Optional: await asyncio.sleep(0.01) # Small yield to prevent hogging
        print(f"Simulation finished after {self._current_step} steps.")

    async def shutdown(self) -> None:
        """Gracefully shut down all systems and the store if needed."""
        print("GraphWorld shutting down...")
        for system in self.systems:
            await system.shutdown()
        # Add any store-specific shutdown if it exists (e.g., closing connections)
        # if hasattr(self.store, 'close'): await self.store.close()
        print("GraphWorld shutdown complete.")

    # --- Utility/Getter methods for the world state (conceptual) ---
    async def get_agent_states_df(self, agent_ids: Optional[List[NodeID]] = None, step: Optional[int] = None) -> Optional[DataFrame]:
        """Retrieve a DataFrame of current states for specified agents (or all)."""
        query_step = step if step is not None else self._current_step -1 # Query last completed step
        if query_step < 0: return None

        # This is a batch query for observation/analysis, not for streaming system input
        # It collects all matching archetypes into one DF.
        all_agent_data = []
        # Assume LLMAgentState is a primary component defining an agent
        async for _, df in self.querier(component_types=(LLMAgentState, GraphNodeComponent), step=query_step):
            if agent_ids:
                df_filtered = df.where(col("GraphNodeComponent__node_id").is_in(agent_ids))
                if len(df_filtered) > 0:
                    all_agent_data.append(df_filtered.to_pandas()) # Collect to pandas for concat
            elif len(df)>0:
                all_agent_data.append(df.to_pandas())
        
        if not all_agent_data:
            return daft.from_pydict({}) # Return empty Daft DataFrame
        
        final_pd_df = pd.concat(all_agent_data, ignore_index=True) if all_agent_data else pd.DataFrame()
        return daft.from_pandas(final_pd_df) if not final_pd_df.empty else daft.from_pydict({})

    async def get_knowledge_graph_view(self, graph_name: str = "default_kg") -> Optional[nx.MultiDiGraph]:
        """ Reconstructs a NetworkX view of a named graph from the GraphStore. """
        # This is a potentially expensive operation for large graphs.
        # It would query all GraphNodeComponent and GraphEdgeComponent tables for that graph_name.
        # For now, it can return the logical_graph if that's kept in sync for small graphs.
        # Or, build it by querying all edges of relevant types.
        
        # Placeholder: returns the in-memory logical graph which is updated on add_edge
        # A full reconstruction would query all edge tables for the graph_name
        # and all entities with GraphNodeComponent belonging to that graph_name.
        if self.store.logical_graph: # and graph_name related filtering if logical_graph becomes complex
            return self.store.logical_graph 
        return None
