from typing import Protocol, Type, Optional, Union, List, Dict
from daft import DataFrame

from archetype.core.base import Component


class iAsyncQuerier(Protocol):
    async def query(self, *component_types: Type[Component], step: int, entities: Optional[Union[int, List[int]]] = None) -> DataFrame: ...

class iAsyncUpdater(Protocol):
    async def update(self, archetypes: Dict[str, DataFrame]): ...

class iAsyncWorld(Protocol):
    def step(self, dt: float): ...
    async def spawn(self, components: List[Component], step: Optional[int] = None) -> int: ...
    async def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    async def remove(self, entity_id: int, comp_type: Type[Component]) -> None: ...