# Copyright 2025 Vangelis Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Set, List, Dict, Tuple, Protocol, Optional, Any, Type
import asyncio
from daft import DataFrame

from archetype.core.interfaces import ArchetypeSignature, Component

class iAsyncStore(Protocol):

    async def remove_entity(self, entity_id: int, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> None: ...
    async def materialize_spawns(self, spawn_cache: Dict[ArchetypeSignature, List[Dict[str, Any]]], world_id: str, run_id: str) -> None: ...
    async def get_archetype_df(self, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> DataFrame: ...
    async def append(self, sig: ArchetypeSignature, df: DataFrame, step: int, world_id: str, run_id: str) -> None: ...
    async def optimize_tables(self) -> None: ...

class iAsyncQuerier(Protocol):
    async def get_archetype(self, sig: ArchetypeSignature, current_step: int, world_id: str, run_id: str) -> Tuple[ArchetypeSignature, DataFrame]: ...
    async def get_archetype_for_entity(self, entity_id: int, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> DataFrame: ...

class iAsyncUpdater(Protocol):
    async def update(self, df: DataFrame, sig: ArchetypeSignature, step: int, world_id: str, run_id: str) -> None: ...
    async def materialize_spawns(self, spawn_cache: Dict[ArchetypeSignature, List[Dict[str, Any]]], world_id: str, run_id: str) -> None: ...
    async def remove_entity(self, entity_id: int, step: int, world_id: str, run_id: str) -> None: ...
class iAsyncProcessor(Protocol):
    async def process(self, df: DataFrame, semaphore: asyncio.Semaphore, *args, **kwargs) -> DataFrame: ...

class iAsyncSystem(Protocol):
    async def add_processor(self, proc: iAsyncProcessor) -> None: ...
    async def remove_processor(self, proc: iAsyncProcessor) -> None: ...
    async def execute(self, querier: iAsyncQuerier, step: int, *args, **kwargs) -> List[Tuple[ArchetypeSignature, DataFrame]]: ...

class iAsyncWorld(Protocol):
    async def step(self, *args, **kwargs): ...
    def get_active_signatures(self) -> Set[Any]: ...
    def spawn(self, *components: Component, step: Optional[int] = None) -> int: ...
    async def update(self, archetypes: List[Tuple[ArchetypeSignature, DataFrame]]) -> None: ...
    async def materialize_spawns(self) -> None: ...
    async def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    async def get_archetype(self, sig: ArchetypeSignature, step: int) -> DataFrame: ...
    async def get_archetype_for_entity(self, entity_id: int, *component_types: Type[Component]) -> DataFrame: ...
    def add_processor(self, proc: iAsyncProcessor) -> None: ...
    def remove_processor(self, proc: iAsyncProcessor) -> None: ...
    def execute(self, df: DataFrame, sig: ArchetypeSignature, step: int, *args, **kwargs) -> DataFrame: ...
