from typing import Set, List, Type, Dict, Tuple, Protocol, Optional
import asyncio
from daft import DataFrame

from archetype.core.interfaces import ArchetypeSignature, Component

class iAsyncStore(Protocol):
    def get_active_signatures(self) -> Set[ArchetypeSignature]: ...
    def add_entity(self, components: List[Component], step: int, world_id: str, run_id: str) -> int: ...
    def remove_entity(self, entity_id: int, step: int, world_id: str, run_id: str) -> None: ...
    def get_archetype_for_entity(self, entity_id: int, *component_types: Type[Component], world_id: str, run_id: str) -> Dict[str, DataFrame]: ...
    def get_archetype(self, sig: ArchetypeSignature, step: int) -> Tuple[ArchetypeSignature, DataFrame]: ...
    def append(self, sig: ArchetypeSignature, df: DataFrame, step: int) -> None: ...
    def optimize_tables(self) -> None: ...

class iAsyncQuerier(Protocol):
    def get_active_signatures(self) -> Set[ArchetypeSignature]: ...
    def get_archetype(self, sig: ArchetypeSignature, step: int) -> Tuple[ArchetypeSignature, DataFrame]: ...
    def get_archetype_for_entity(self, entity_id: int, *component_types: Type[Component]) -> Dict[str, DataFrame]: ...

class iAsyncUpdater(Protocol):
    def append(self, sig: ArchetypeSignature, df: DataFrame, step: int) -> None: ...

class iAsyncProcessor(Protocol):
    async def process(self, df: DataFrame, semaphore: asyncio.Semaphore, *args, **kwargs) -> DataFrame: ...

class iAsyncSystem(Protocol):
    async def add_processor(self, proc: iAsyncProcessor) -> None: ...
    async def remove_processor(self, proc: iAsyncProcessor) -> None: ...
    async def execute(self, querier: iAsyncQuerier, step: int, *args, **kwargs) -> List[Tuple[ArchetypeSignature, DataFrame]]: ...

class iAsyncWorld(Protocol):
    def add_processor(self, proc: iAsyncProcessor) -> None: ...
    def remove_processor(self, proc: iAsyncProcessor) -> None: ...
    def spawn(self, *components: Component, step: Optional[int] = None) -> int: ...
    def despawn(self, entity_id: int, step: Optional[int] = None) -> None: ...
    def materialize_spawns(self) -> None: ...
    async def step(self, dt: float): ...
