#!/usr/bin/env python3
# Copyright 2025 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate CLI reference markdown from Typer/Click introspection.

Usage:
    python scripts/generate_cli_docs.py

Writes docs/reference/cli.md.
"""

from __future__ import annotations

from pathlib import Path

import click
import typer.main

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "reference"
OUTPUT = DOCS_DIR / "cli.md"


def get_click_app() -> click.Group:
    """Convert the Typer app to a Click group for introspection."""
    from archetype.cli.main import app

    return typer.main.get_command(app)


def render_params(params: list[click.Parameter]) -> list[str]:
    """Render command parameters as a markdown table."""
    arguments = [p for p in params if isinstance(p, click.Argument)]
    options = [p for p in params if isinstance(p, click.Option) and p.name != "help"]

    lines: list[str] = []

    if arguments:
        lines.append("**Arguments:**")
        lines.append("")
        lines.append("| Name | Type | Required | Description |")
        lines.append("|------|------|----------|-------------|")
        for arg in arguments:
            typ = arg.type.name if hasattr(arg.type, "name") else str(arg.type)
            req = "Yes" if arg.required else "No"
            help_text = getattr(arg, "help", "") or ""
            lines.append(f"| `{arg.human_readable_name}` | {typ} | {req} | {help_text} |")
        lines.append("")

    if options:
        lines.append("**Options:**")
        lines.append("")
        lines.append("| Flag | Type | Default | Description |")
        lines.append("|------|------|---------|-------------|")
        for opt in options:
            flag = " / ".join(f"`{d}`" for d in opt.opts)
            if opt.secondary_opts:
                flag += " / " + " / ".join(f"`{d}`" for d in opt.secondary_opts)
            typ = opt.type.name if hasattr(opt.type, "name") else str(opt.type)
            default = opt.default
            if default is None:
                default = "—"
            else:
                default = f"`{default}`"
            help_text = opt.help or ""
            lines.append(f"| {flag} | {typ} | {default} | {help_text} |")
        lines.append("")

    return lines


def render_command(name: str, cmd: click.Command, prefix: str = "archetype") -> list[str]:
    """Render a single command as markdown."""
    full_name = f"{prefix} {name}"
    lines: list[str] = []

    lines.append(f"### `{full_name}`")
    lines.append("")

    help_text = cmd.help or cmd.short_help or ""
    if help_text:
        lines.append(help_text)
        lines.append("")

    lines.append("```bash")
    # Build usage line
    usage_parts = [full_name]
    for param in cmd.params:
        if isinstance(param, click.Argument):
            if param.required:
                usage_parts.append(f"<{param.human_readable_name}>")
            else:
                usage_parts.append(f"[{param.human_readable_name}]")
    options = [p for p in cmd.params if isinstance(p, click.Option) and p.name != "help"]
    if options:
        usage_parts.append("[OPTIONS]")
    lines.append(" ".join(usage_parts))
    lines.append("```")
    lines.append("")

    param_lines = render_params(cmd.params)
    if param_lines:
        lines.extend(param_lines)

    lines.append("---")
    lines.append("")
    return lines


def render_group(
    name: str, group: click.Group, prefix: str = "archetype"
) -> list[str]:
    """Render a command group and all its subcommands."""
    full_name = f"{prefix} {name}"
    lines: list[str] = []

    lines.append(f"## `{full_name}`")
    lines.append("")

    help_text = group.help or group.short_help or ""
    if help_text:
        lines.append(help_text)
        lines.append("")

    for cmd_name, cmd in sorted(group.commands.items()):
        if isinstance(cmd, click.Group):
            lines.extend(render_group(cmd_name, cmd, prefix=full_name))
        else:
            lines.extend(render_command(cmd_name, cmd, prefix=full_name))

    return lines


def generate() -> str:
    """Generate the full CLI reference markdown."""
    app = get_click_app()
    lines: list[str] = []

    lines.append("<!-- Auto-generated by scripts/generate_cli_docs.py — do not edit -->")
    lines.append("")
    lines.append("# CLI Reference")
    lines.append("")
    lines.append(
        "The `archetype` CLI is built with [Typer](https://typer.tiangolo.com/). "
        "Install via `uv sync` or `pip install -e .`."
    )
    lines.append("")
    lines.append(
        "The CLI is a thin HTTP client — every command (except `serve`) "
        "delegates to a running `archetype serve` instance."
    )
    lines.append("")

    # Separate top-level commands from subgroups
    top_commands: list[tuple[str, click.Command]] = []
    subgroups: list[tuple[str, click.Group]] = []

    for cmd_name, cmd in sorted(app.commands.items()):
        if isinstance(cmd, click.Group):
            subgroups.append((cmd_name, cmd))
        else:
            top_commands.append((cmd_name, cmd))

    if top_commands:
        lines.append("## Commands")
        lines.append("")
        for cmd_name, cmd in top_commands:
            lines.extend(render_command(cmd_name, cmd))

    for group_name, group in subgroups:
        lines.extend(render_group(group_name, group))

    return "\n".join(lines)


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
