#!/usr/bin/env python3
# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate the tiered Python reference and top-level exposure inventory."""

from __future__ import annotations

import argparse
import types
from collections.abc import Iterable, Mapping
from dataclasses import MISSING, dataclass, fields, is_dataclass
from enum import Enum
from importlib import import_module
from pathlib import Path
from typing import Annotated, Any, Union, get_args, get_origin

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "reference"
OUTPUT = DOCS_DIR / "python-api.md"
PAGES_DIR = DOCS_DIR / "python"
GENERATED = "<!-- Auto-generated by scripts/generate_python_api_docs.py — do not edit -->"


@dataclass(frozen=True)
class ReferencePage:
    slug: str
    title: str
    tier: str
    introduction: str
    names: tuple[str, ...]


PAGES: tuple[ReferencePage, ...] = (
    ReferencePage(
        "runtime",
        "Runtime",
        "Recommended API",
        "Start here for scripts, notebooks, and applications. A runtime owns process-level "
        "services and creates world handles.",
        ("ArchetypeRuntime", "configure_session", "entrypoint", "public_api"),
    ),
    ReferencePage(
        "world-handle",
        "World handle",
        "Recommended API",
        "Create entities, run simulations, query history, and manage one world.",
        ("RuntimeWorld",),
    ),
    ReferencePage(
        "runtime-models",
        "Runtime models",
        "Recommended API",
        "Configuration, result, and introspection records returned by world operations.",
        (
            "ProcessorInfo",
            "HookInfo",
            "ResourceInfo",
            "WorldInfo",
            "RunResult",
            "EpisodeConfig",
            "EpisodeResult",
            "RolloutConfig",
            "RolloutResult",
        ),
    ),
    ReferencePage(
        "artifacts",
        "File artifacts",
        "Recommended API",
        "Declare files, configure content-addressed storage, retain portable "
        "references to indexed artifact occurrences, and anchor interpretation to a task.",
        (
            "ArtifactContext",
            "ArtifactSource",
            "ArtifactRef",
            "ArtifactStoreConfig",
            "analyze_artifacts",
            "synthesize_artifact_context",
        ),
    ),
    ReferencePage(
        "transcripts",
        "Coding-agent transcripts",
        "Recommended API",
        "Ingest Claude Code JSONL through a redacted artifact boundary and append "
        "normalized mission rows linked to the sanitized file occurrence.",
        (
            "ClaudeTranscriptSource",
            "TranscriptIngestionResult",
        ),
    ),
    ReferencePage(
        "building-blocks",
        "Building blocks",
        "Extension API",
        "Use these types to define component data, processors, and processor resources.",
        ("Component", "AsyncProcessor", "Resources"),
    ),
    ReferencePage(
        "hooks",
        "Hooks and ingress identity",
        "Extension API",
        "React to world lifecycle events and define the identity record used by trusted ingress adapters.",
        (
            "ActorCtx",
            "HookEvent",
            "PreTick",
            "PostTick",
            "OnSpawn",
            "OnDespawn",
            "OnComponentAdded",
            "OnComponentRemoved",
            "OnDestroy",
            "HookHandle",
        ),
    ),
    ReferencePage(
        "configuration",
        "Configuration",
        "Recommended API",
        "Runtime configuration is user-facing. `WorldConfig` is primarily for custom hosts "
        "and lower-level engine construction.",
        ("StorageBackend", "StorageConfig", "CacheConfig", "RunConfig", "WorldConfig"),
    ),
    ReferencePage(
        "autoresearch",
        "AutoResearch and evaluation",
        "Extension API",
        "Configure optimization loops and persist evaluation evidence with explicit identities.",
        (
            "AutoResearchConfig",
            "AutoResearchResult",
            "ResearchCandidateContext",
            "EvaluationResult",
            "IterationResult",
            "FrameGrader",
            "Outcome",
            "GraderContract",
            "EvalReceipt",
        ),
    ),
    ReferencePage(
        "physical-ai",
        "Physical AI",
        "Recommended API",
        "Run or recover complete Modal-hosted episode batches through a World.",
        (
            "HostedEpisodeRequest",
            "HostedEpisodeObservation",
            "ModalHostedEpisodeConfig",
            "EnvClient",
            "PolicyClient",
            "PerturbationStrategy",
            "TemplatePerturbation",
            "RoundRecord",
            "OptimizationResult",
            "optimize_instruction",
        ),
    ),
    ReferencePage(
        "core",
        "Core engine",
        "Extension API",
        "Supported engine primitives for custom execution and world lifecycle extensions.",
        (
            "Archetype",
            "ArchetypeSignature",
            "AsyncWorld",
            "AsyncSystem",
            "AsyncQueryManager",
            "AsyncUpdateManager",
            "AmbiguousTickCommitError",
            "TickExecutionError",
            "TickFailure",
        ),
    ),
    ReferencePage(
        "storage",
        "Storage backends",
        "Integration API",
        "Supported asynchronous storage implementations for custom engine wiring.",
        ("AsyncStore", "AsyncCachedStore", "AsyncLancedbStore"),
    ),
    ReferencePage(
        "compatibility",
        "Compatibility API",
        "Compatibility API",
        "The synchronous educational engine and legacy aliases remain available for "
        "compatibility. New application code should use `ArchetypeRuntime`.",
        (
            "SyncArchetypeRuntime",
            "SyncRuntimeWorld",
            "run_sync",
            "SyncProcessor",
            "SyncWorld",
            "SyncSystem",
            "SyncStore",
            "QueryManager",
            "UpdateManager",
        ),
    ),
)

ALIASES: dict[str, str] = {
    "CandidateContext": "ResearchCandidateContext",
    "Processor": "SyncProcessor",
    "World": "SyncWorld",
    "System": "SyncSystem",
    "Store": "SyncStore",
    "Querier": "QueryManager",
    "Updater": "UpdateManager",
}

# These types are part of the public signature closure but are intentionally
# namespaced rather than promoted to the top-level import surface.
SUPPLEMENTAL: dict[str, tuple[str, str]] = {
    "analyze_artifacts": ("archetype.artifacts.context", "analyze_artifacts"),
    "synthesize_artifact_context": (
        "archetype.artifacts.context",
        "synthesize_artifact_context",
    ),
    "ActorCtx": ("archetype.commands.models", "ActorCtx"),
    "HookEvent": ("archetype.core.hooks", "HookEvent"),
    "HookHandle": ("archetype.core.hooks", "HookHandle"),
    "HookInfo": ("archetype.world.models", "HookInfo"),
    "ClaudeTranscriptSource": (
        "archetype.missions.trajectories",
        "ClaudeTranscriptSource",
    ),
    "TranscriptIngestionResult": (
        "archetype.missions.trajectories",
        "TranscriptIngestionResult",
    ),
    "IterationResult": ("archetype.research.models", "IterationResult"),
    "EnvClient": ("archetype.physical_ai.interfaces", "EnvClient"),
    "OptimizationResult": ("archetype.physical_ai.optimization", "OptimizationResult"),
    "PerturbationStrategy": (
        "archetype.physical_ai.optimization",
        "PerturbationStrategy",
    ),
    "PolicyClient": ("archetype.physical_ai.interfaces", "PolicyClient"),
    "RoundRecord": ("archetype.physical_ai.optimization", "RoundRecord"),
    "TemplatePerturbation": (
        "archetype.physical_ai.optimization",
        "TemplatePerturbation",
    ),
    "optimize_instruction": (
        "archetype.physical_ai.optimization",
        "optimize_instruction",
    ),
    "ProcessorInfo": ("archetype.world.models", "ProcessorInfo"),
    "ResourceInfo": ("archetype.world.models", "ResourceInfo"),
    "StorageBackend": ("archetype.core.config", "StorageBackend"),
    "PreTick": ("archetype.core.hooks", "PreTick"),
    "PostTick": ("archetype.core.hooks", "PostTick"),
    "OnSpawn": ("archetype.core.hooks", "OnSpawn"),
    "OnDespawn": ("archetype.core.hooks", "OnDespawn"),
    "OnComponentAdded": ("archetype.core.hooks", "OnComponentAdded"),
    "OnComponentRemoved": ("archetype.core.hooks", "OnComponentRemoved"),
    "OnDestroy": ("archetype.core.hooks", "OnDestroy"),
}

# Record-like types read better as a compact field table than as dozens of
# empty attribute headings containing Pydantic Field(...) representations.
RECORDS = frozenset(
    {
        "StorageConfig",
        "StorageBackend",
        "CacheConfig",
        "RunConfig",
        "WorldConfig",
        "WorldInfo",
        "RunResult",
        "EpisodeConfig",
        "EpisodeResult",
        "RolloutConfig",
        "RolloutResult",
        "ArtifactContext",
        "ArtifactSource",
        "ArtifactRef",
        "ArtifactStoreConfig",
        "ClaudeTranscriptSource",
        "TranscriptIngestionResult",
        "ProcessorInfo",
        "HookInfo",
        "ResourceInfo",
        "ActorCtx",
        "HookEvent",
        "PreTick",
        "PostTick",
        "OnSpawn",
        "OnDespawn",
        "OnComponentAdded",
        "OnComponentRemoved",
        "OnDestroy",
        "AutoResearchConfig",
        "AutoResearchResult",
        "ResearchCandidateContext",
        "EvaluationResult",
        "IterationResult",
        "FrameGrader",
        "Outcome",
        "GraderContract",
        "EvalReceipt",
        "HostedEpisodeRequest",
        "HostedEpisodeObservation",
        "ModalHostedEpisodeConfig",
        "OptimizationResult",
        "RoundRecord",
    }
)

EXPLICIT_MEMBERS: dict[str, tuple[str, ...]] = {
    "RunConfig": ("dev", "benchmark"),
    "AutoResearchResult": ("improved",),
    "ArtifactStoreConfig": ("local",),
    "GraderContract": ("digest",),
}

COMPATIBILITY_CLASSES = frozenset(
    {
        "SyncArchetypeRuntime",
        "SyncRuntimeWorld",
        "SyncProcessor",
        "SyncWorld",
        "SyncSystem",
        "SyncStore",
        "QueryManager",
        "UpdateManager",
    }
)

HIDDEN_SIGNATURES = frozenset({"RuntimeWorld", "SyncRuntimeWorld"})


def _manifest_root_exports(
    manifests: Iterable[object],
    *,
    framework_locations: Mapping[str, tuple[str, str]],
) -> dict[str, tuple[str, str]]:
    """Merge deterministic compatibility exports without weakening collisions."""

    exports: dict[str, tuple[str, str]] = {}
    owners: dict[str, str] = {}
    for manifest in manifests:
        library = str(getattr(manifest, "name", ""))
        root_exports = getattr(manifest, "root_exports", None)
        if not isinstance(root_exports, Mapping):
            raise TypeError(f"world library {library!r} has no root-export mapping")
        for name, target in root_exports.items():
            if name in framework_locations:
                raise RuntimeError(
                    f"world library {library!r} root export {name!r} collides with the framework"
                )
            previous = owners.get(name)
            if previous is not None:
                raise RuntimeError(
                    f"duplicate world-library root export {name!r} from "
                    f"{previous!r} and {library!r}"
                )
            if not (
                isinstance(name, str)
                and isinstance(target, tuple)
                and len(target) == 2
                and all(isinstance(value, str) and value for value in target)
            ):
                raise TypeError(f"world library {library!r} has an invalid root-export location")
            owners[name] = library
            exports[name] = target
    return exports


def _validate_coverage() -> dict[str, tuple[str, str]]:
    """Return export locations after checking classification and alias coverage."""
    import archetype
    from archetype.world_libraries import discover_world_libraries

    framework_locations = dict(archetype._EXPORTS)
    framework_exports = set(archetype.__all__)
    if framework_exports != set(framework_locations):
        raise RuntimeError("framework __all__ and _EXPORTS disagree")
    manifests = discover_world_libraries(framework_version=archetype.__version__)
    compatibility_locations = _manifest_root_exports(
        manifests,
        framework_locations=framework_locations,
    )
    compatibility_exports = set(compatibility_locations)
    supplemental_collisions = sorted(
        set(SUPPLEMENTAL) & (framework_exports | compatibility_exports)
    )
    if supplemental_collisions:
        raise RuntimeError(
            "supplemental locations collide with root exports: "
            + ", ".join(supplemental_collisions)
        )

    documented = {name for page in PAGES for name in page.names}
    top_level_documented = (documented - set(SUPPLEMENTAL)) | set(ALIASES)
    actual = framework_exports | compatibility_exports
    missing = sorted(actual - top_level_documented)
    stale = sorted(top_level_documented - actual)
    duplicates = sorted(
        name
        for name in documented
        if sum(name in page.names for page in PAGES) + int(name in ALIASES) > 1
    )
    if missing or stale or duplicates:
        problems = []
        if missing:
            problems.append(f"unclassified top-level exports: {', '.join(missing)}")
        if stale:
            problems.append(f"classified names not exported at top level: {', '.join(stale)}")
        if duplicates:
            problems.append(f"exports assigned more than once: {', '.join(duplicates)}")
        raise RuntimeError("; ".join(problems))

    return {**framework_locations, **compatibility_locations, **SUPPLEMENTAL}


def _type_name(annotation: object) -> str:
    """Render a compact Python type name for a generated field table."""
    if annotation is Any:
        return "Any"
    if annotation is Ellipsis:
        return "..."
    if annotation is None or annotation is type(None):
        return "None"

    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _type_name(args[0])
    if origin in (Union, types.UnionType):
        return " | ".join(_type_name(arg) for arg in args)
    if origin is not None:
        name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if args:
            return f"{name}[{', '.join(_type_name(arg) for arg in args)}]"
        return name

    return getattr(annotation, "__name__", str(annotation).replace("typing.", ""))


def _default_name(default: object, factory: object | None, required: bool) -> str:
    if required:
        return "required"
    if factory is not None:
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"generated by {name}"
    if isinstance(default, Enum):
        return repr(default.value)
    return repr(default)


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _record_rows(record: type) -> list[tuple[str, str, str, str]]:
    if issubclass(record, Enum):
        return [(member.name, record.__name__, repr(member.value), "—") for member in record]

    if hasattr(record, "model_fields"):
        rows = []
        for name, info in record.model_fields.items():
            rows.append(
                (
                    name,
                    _type_name(info.annotation),
                    _default_name(info.default, info.default_factory, info.is_required()),
                    info.description or "—",
                )
            )
        return rows

    if is_dataclass(record):
        rows = []
        for info in fields(record):
            required = info.default is MISSING and info.default_factory is MISSING
            factory = None if info.default_factory is MISSING else info.default_factory
            default = None if info.default is MISSING else info.default
            rows.append(
                (
                    info.name,
                    _type_name(info.type),
                    _default_name(default, factory, required),
                    "—",
                )
            )
        return rows

    return []


def _record_table(name: str, locations: dict[str, tuple[str, str]]) -> list[str]:
    module_name, attribute = locations[name]
    record = getattr(import_module(module_name), attribute)
    rows = _record_rows(record)
    if not rows:
        return []

    show_descriptions = any(description != "—" for *_, description in rows)
    lines = (
        ["| Field | Type | Default | Description |", "| --- | --- | --- | --- |"]
        if show_descriptions
        else ["| Field | Type | Default |", "| --- | --- | --- |"]
    )
    for field_name, annotation, default, description in rows:
        cells = [
            f"`{_escape_cell(field_name)}`",
            f"`{_escape_cell(annotation)}`",
            f"`{_escape_cell(default)}`",
        ]
        if show_descriptions:
            cells.append(_escape_cell(description))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def _directive(name: str, locations: dict[str, tuple[str, str]]) -> list[str]:
    module, attribute = locations[name]
    lines = [f"::: {module}.{attribute}"]
    options: list[str] = []
    members = EXPLICIT_MEMBERS.get(name)
    if members:
        options.append("      members:")
        options.extend(f"        - {member}" for member in members)
    elif name in RECORDS or name in COMPATIBILITY_CLASSES:
        options.append("      members: false")
    if name in HIDDEN_SIGNATURES:
        options.append("      show_signature: false")
    if options:
        lines.append("    options:")
        lines.extend(options)
    lines.append("")
    return lines


def _render_page(page: ReferencePage, locations: dict[str, tuple[str, str]]) -> str:
    lines = [
        GENERATED,
        "",
        f"# {page.title}",
        "",
        f"**{page.tier}.** {page.introduction}",
        "",
    ]
    for name in page.names:
        lines.extend(_directive(name, locations))
        if name in RECORDS:
            lines.extend(_record_table(name, locations))
    return "\n".join(lines)


def _render_index() -> str:
    lines = [
        GENERATED,
        "",
        "# Python API",
        "",
        "Archetype's Python reference inventories and classifies the supported "
        "top-level surface. Most "
        "applications only need the runtime, world-handle, and building-block pages.",
        "",
        "| Surface | Use it for |",
        "| --- | --- |",
    ]
    for page in PAGES:
        lines.append(f"| [{page.title}](python/{page.slug}.md) | {page.introduction} |")
    lines.extend(
        (
            "",
            "## Classification rule",
            "",
            "Presence in `archetype.__all__` is an intentional supported exposure. The tier "
            "on each reference page and the focused specifications classify its stability. "
            "Types exposed by supported "
            "signatures are part of those contracts even when they are not top-level exports.",
            "",
            "Installed world libraries may contribute Compatibility-tier root attributes through "
            "their deterministic manifests. Those names remain deliberately absent from the "
            "domain-free framework `archetype.__all__`; new code should import the owning "
            "`archetype.<family>` module or its typed adapter explicitly.",
            "",
            "The container and concrete application services are internal and are not "
            "top-level exports. Repository wiring imports them from their owning family "
            "modules; applications use the runtime or an adapter.",
            "",
            "See [API stability and docstrings](../guide/api-stability.md) for the full policy.",
            "",
            "## Compatibility aliases",
            "",
        )
    )
    for alias, target in ALIASES.items():
        lines.append(f"- `{alias}` is an alias for `{target}`.")
    lines.append("")
    return "\n".join(lines)


def _expected_outputs(locations: dict[str, tuple[str, str]]) -> dict[Path, str]:
    outputs = {OUTPUT: _render_index()}
    for page in PAGES:
        outputs[PAGES_DIR / f"{page.slug}.md"] = _render_page(page, locations)
    return outputs


def _check_outputs(outputs: dict[Path, str]) -> list[Path]:
    drifted = [
        destination
        for destination, expected in outputs.items()
        if not destination.is_file() or destination.read_text(encoding="utf-8") != expected
    ]
    drifted.extend(stale for stale in PAGES_DIR.glob("*.md") if stale not in outputs)
    return sorted(drifted)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed Python reference differs from generated output",
    )
    args = parser.parse_args(argv)

    locations = _validate_coverage()
    outputs = _expected_outputs(locations)
    if args.check:
        drifted = _check_outputs(outputs)
        if drifted:
            rendered = ", ".join(str(path.relative_to(DOCS_DIR.parent)) for path in drifted)
            print(f"Python API reference is stale: {rendered}")
            return 1
        print(f"Python API reference is current ({len(PAGES)} pages)")
        return 0

    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    for destination, rendered in outputs.items():
        destination.write_text(rendered, encoding="utf-8", newline="\n")
    for stale in PAGES_DIR.glob("*.md"):
        if stale not in outputs:
            stale.unlink()
    print(f"Generated {OUTPUT} and {len(PAGES)} Python API pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
