#!/usr/bin/env python3
# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate the Python reference from Archetype's public export contract.

The page deliberately documents the supported top-level API before lower-level
engine and service interfaces. The coverage check makes a public-export change
fail the docs build until it is assigned to a reference section.
"""

from __future__ import annotations

from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "reference"
OUTPUT = DOCS_DIR / "python-api.md"

# Keep this order intentional: scripts should begin at Runtime, while core and
# app surfaces remain available to advanced users below it.
SECTIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "Runtime",
        (
            "ArchetypeRuntime",
            "RuntimeWorld",
            "SyncArchetypeRuntime",
            "SyncRuntimeWorld",
            "run_sync",
            "configure_session",
        ),
    ),
    (
        "Components and processors",
        (
            "Component",
            "Archetype",
            "ArchetypeSignature",
            "Resources",
            "SyncProcessor",
            "AsyncProcessor",
        ),
    ),
    (
        "Core engine",
        (
            "SyncWorld",
            "AsyncWorld",
            "SyncSystem",
            "AsyncSystem",
            "SyncStore",
            "AsyncStore",
            "AsyncCachedStore",
            "AsyncLancedbStore",
            "QueryManager",
            "UpdateManager",
            "AsyncQueryManager",
            "AsyncUpdateManager",
        ),
    ),
    (
        "Configuration",
        ("StorageConfig", "CacheConfig", "RunConfig", "WorldConfig"),
    ),
    (
        "Service layer",
        (
            "CommandBroker",
            "WorldService",
            "StorageService",
            "CommandService",
            "SimulationService",
            "QueryService",
            "ServiceContainer",
            "Command",
            "CommandType",
        ),
    ),
    (
        "AutoResearch",
        (
            "AutoResearchConfig",
            "AutoResearchResult",
            "CandidateContext",
            "EvaluationResult",
        ),
    ),
)

ALIASES: dict[str, str] = {
    "Processor": "SyncProcessor",
    "World": "SyncWorld",
    "System": "SyncSystem",
    "Store": "SyncStore",
    "Querier": "QueryManager",
    "Updater": "UpdateManager",
}


def _validate_coverage() -> dict[str, tuple[str, str]]:
    """Return public export locations after checking full reference coverage."""
    import archetype

    documented = {name for _, names in SECTIONS for name in names} | set(ALIASES)
    actual = set(archetype.__all__)
    missing = sorted(actual - documented)
    stale = sorted(documented - actual)
    if missing or stale:
        problems = []
        if missing:
            problems.append(f"undocumented public exports: {', '.join(missing)}")
        if stale:
            problems.append(f"non-public documented names: {', '.join(stale)}")
        raise RuntimeError("; ".join(problems))

    return archetype._EXPORTS


def generate() -> str:
    """Render a mkdocstrings directive for every canonical public export."""
    locations = _validate_coverage()
    lines = [
        "<!-- Auto-generated by scripts/generate_python_api_docs.py — do not edit -->",
        "",
        "# Python API Reference",
        "",
        "This page is generated from Archetype's public export contract. Start with",
        "`ArchetypeRuntime` for a script. The core and service-layer sections are",
        "lower-level interfaces for engine extensions and custom hosts.",
        "",
    ]

    for heading, names in SECTIONS:
        lines.extend((f"## {heading}", ""))
        for name in names:
            module, attribute = locations[name]
            lines.extend((f"::: {module}.{attribute}", ""))

    lines.extend(("## Compatibility aliases", ""))
    for alias, target in ALIASES.items():
        lines.append(f"- `{alias}` is an alias for `{target}`.")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
