#!/usr/bin/env python3
# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate the tiered Python reference from Archetype's public API contract."""

from __future__ import annotations

import types
from dataclasses import MISSING, dataclass, fields, is_dataclass
from enum import Enum
from importlib import import_module
from pathlib import Path
from typing import Annotated, Any, Union, get_args, get_origin

DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "reference"
OUTPUT = DOCS_DIR / "python-api.md"
PAGES_DIR = DOCS_DIR / "python"
GENERATED = "<!-- Auto-generated by scripts/generate_python_api_docs.py — do not edit -->"


@dataclass(frozen=True)
class ReferencePage:
    slug: str
    title: str
    tier: str
    introduction: str
    names: tuple[str, ...]


PAGES: tuple[ReferencePage, ...] = (
    ReferencePage(
        "runtime",
        "Runtime",
        "Recommended API",
        "Start here for scripts, notebooks, and applications. A runtime owns process-level "
        "services and creates world handles.",
        ("ArchetypeRuntime", "configure_session", "entrypoint", "public_api"),
    ),
    ReferencePage(
        "world-handle",
        "World handle",
        "Recommended API",
        "Create entities, run simulations, query history, and manage one world.",
        ("RuntimeWorld",),
    ),
    ReferencePage(
        "runtime-models",
        "Runtime models",
        "Recommended API",
        "Configuration, result, receipt, and introspection records returned by world operations.",
        (
            "ProcessorInfo",
            "HookInfo",
            "ResourceInfo",
            "WorldInfo",
            "RunResult",
            "EpisodeConfig",
            "EpisodeResult",
            "RolloutConfig",
            "RolloutResult",
            "FactReceipt",
            "FactWriteReceipt",
        ),
    ),
    ReferencePage(
        "building-blocks",
        "Building blocks",
        "Extension API",
        "Use these types to define component data, processors, and processor resources.",
        ("Component", "AsyncProcessor", "FactProcessor", "Resources"),
    ),
    ReferencePage(
        "hooks",
        "Hooks and identity",
        "Extension API",
        "Bind an actor identity to a world handle and react to world lifecycle events.",
        (
            "ActorCtx",
            "HookEvent",
            "PreTick",
            "PostTick",
            "OnSpawn",
            "OnDespawn",
            "OnComponentAdded",
            "OnComponentRemoved",
            "OnDestroy",
            "HookHandle",
        ),
    ),
    ReferencePage(
        "configuration",
        "Configuration",
        "Recommended API",
        "Runtime configuration is user-facing. `WorldConfig` is primarily for custom hosts "
        "and lower-level engine construction.",
        ("StorageBackend", "StorageConfig", "CacheConfig", "RunConfig", "WorldConfig"),
    ),
    ReferencePage(
        "autoresearch",
        "AutoResearch and evaluation",
        "Extension API",
        "Configure optimization loops and persist evaluation evidence with explicit identities.",
        (
            "AutoResearchConfig",
            "AutoResearchResult",
            "CandidateContext",
            "EvaluationResult",
            "IterationResult",
            "Outcome",
            "GraderContract",
            "EvalReceipt",
        ),
    ),
    ReferencePage(
        "artifacts",
        "Artifact finalization",
        "Integration API",
        "Publish checkpoint-qualified sandbox evidence, query its durable index, and "
        "reconcile interrupted publications.",
        (
            "ArtifactStoreConfig",
            "ArtifactCandidate",
            "ArtifactBundleRequest",
            "ArtifactIndexRecord",
            "ArtifactPublishReceipt",
            "ArtifactReconcileResult",
            "ArtifactSourceResolver",
            "ArtifactService",
        ),
    ),
    ReferencePage(
        "services",
        "Service integration",
        "Integration API",
        "Use the service layer when a host needs explicit authorization, command routing, "
        "or custom process wiring. Most scripts should use the runtime instead.",
        (
            "ServiceContainer",
            "CommandService",
            "WorldService",
            "SimulationService",
            "QueryService",
            "FactService",
            "StorageService",
            "CommandBroker",
            "Command",
            "CommandType",
        ),
    ),
    ReferencePage(
        "core",
        "Core engine",
        "Extension API",
        "Supported engine primitives for custom execution and world lifecycle extensions.",
        (
            "Archetype",
            "ArchetypeSignature",
            "AsyncWorld",
            "AsyncSystem",
            "AsyncQueryManager",
            "AsyncUpdateManager",
        ),
    ),
    ReferencePage(
        "storage",
        "Storage backends",
        "Integration API",
        "Supported asynchronous storage implementations for custom engine wiring.",
        ("AsyncStore", "AsyncCachedStore", "AsyncLancedbStore"),
    ),
    ReferencePage(
        "compatibility",
        "Compatibility API",
        "Compatibility API",
        "The synchronous educational engine and legacy aliases remain available for "
        "compatibility. New application code should use `ArchetypeRuntime`.",
        (
            "SyncArchetypeRuntime",
            "SyncRuntimeWorld",
            "run_sync",
            "SyncProcessor",
            "SyncWorld",
            "SyncSystem",
            "SyncStore",
            "QueryManager",
            "UpdateManager",
        ),
    ),
)

ALIASES: dict[str, str] = {
    "Processor": "SyncProcessor",
    "World": "SyncWorld",
    "System": "SyncSystem",
    "Store": "SyncStore",
    "Querier": "QueryManager",
    "Updater": "UpdateManager",
}

# These types are part of the public signature closure but are intentionally
# namespaced rather than promoted to the top-level import surface.
SUPPLEMENTAL: dict[str, tuple[str, str]] = {
    "ActorCtx": ("archetype.app.auth", "ActorCtx"),
    "HookEvent": ("archetype.core.hooks", "HookEvent"),
    "HookHandle": ("archetype.core.hooks", "HookHandle"),
    "HookInfo": ("archetype.app.models", "HookInfo"),
    "IterationResult": ("archetype.app.autoresearch_service", "IterationResult"),
    "ProcessorInfo": ("archetype.app.models", "ProcessorInfo"),
    "ResourceInfo": ("archetype.app.models", "ResourceInfo"),
    "StorageBackend": ("archetype.core.config", "StorageBackend"),
    "PreTick": ("archetype.core.hooks", "PreTick"),
    "PostTick": ("archetype.core.hooks", "PostTick"),
    "OnSpawn": ("archetype.core.hooks", "OnSpawn"),
    "OnDespawn": ("archetype.core.hooks", "OnDespawn"),
    "OnComponentAdded": ("archetype.core.hooks", "OnComponentAdded"),
    "OnComponentRemoved": ("archetype.core.hooks", "OnComponentRemoved"),
    "OnDestroy": ("archetype.core.hooks", "OnDestroy"),
}

# Record-like types read better as a compact field table than as dozens of
# empty attribute headings containing Pydantic Field(...) representations.
RECORDS = frozenset(
    {
        "StorageConfig",
        "StorageBackend",
        "CacheConfig",
        "RunConfig",
        "WorldConfig",
        "WorldInfo",
        "RunResult",
        "EpisodeConfig",
        "EpisodeResult",
        "RolloutConfig",
        "RolloutResult",
        "FactReceipt",
        "FactWriteReceipt",
        "ArtifactStoreConfig",
        "ArtifactCandidate",
        "ArtifactBundleRequest",
        "ArtifactIndexRecord",
        "ArtifactPublishReceipt",
        "ArtifactReconcileResult",
        "ProcessorInfo",
        "HookInfo",
        "ResourceInfo",
        "ActorCtx",
        "HookEvent",
        "PreTick",
        "PostTick",
        "OnSpawn",
        "OnDespawn",
        "OnComponentAdded",
        "OnComponentRemoved",
        "OnDestroy",
        "AutoResearchConfig",
        "AutoResearchResult",
        "CandidateContext",
        "EvaluationResult",
        "IterationResult",
        "Outcome",
        "GraderContract",
        "EvalReceipt",
    }
)

EXPLICIT_MEMBERS: dict[str, tuple[str, ...]] = {
    "RunConfig": ("dev", "benchmark"),
    "AutoResearchResult": ("improved",),
    "FactWriteReceipt": ("duplicate",),
    "GraderContract": ("digest",),
}

COMPATIBILITY_CLASSES = frozenset(
    {
        "SyncArchetypeRuntime",
        "SyncRuntimeWorld",
        "SyncProcessor",
        "SyncWorld",
        "SyncSystem",
        "SyncStore",
        "QueryManager",
        "UpdateManager",
    }
)

HIDDEN_SIGNATURES = frozenset({"RuntimeWorld", "SyncRuntimeWorld"})


def _validate_coverage() -> dict[str, tuple[str, str]]:
    """Return export locations after checking tier and alias coverage."""
    import archetype

    documented = {name for page in PAGES for name in page.names}
    top_level_documented = (documented - set(SUPPLEMENTAL)) | set(ALIASES)
    actual = set(archetype.__all__)
    missing = sorted(actual - top_level_documented)
    stale = sorted(top_level_documented - actual)
    duplicates = sorted(
        name
        for name in documented
        if sum(name in page.names for page in PAGES) + int(name in ALIASES) > 1
    )
    if missing or stale or duplicates:
        problems = []
        if missing:
            problems.append(f"undocumented public exports: {', '.join(missing)}")
        if stale:
            problems.append(f"non-public documented names: {', '.join(stale)}")
        if duplicates:
            problems.append(f"exports assigned more than once: {', '.join(duplicates)}")
        raise RuntimeError("; ".join(problems))

    return {**archetype._EXPORTS, **SUPPLEMENTAL}


def _type_name(annotation: object) -> str:
    """Render a compact Python type name for a generated field table."""
    if annotation is Any:
        return "Any"
    if annotation is None or annotation is type(None):
        return "None"

    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _type_name(args[0])
    if origin in (Union, types.UnionType):
        return " | ".join(_type_name(arg) for arg in args)
    if origin is not None:
        name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if args:
            return f"{name}[{', '.join(_type_name(arg) for arg in args)}]"
        return name

    return getattr(annotation, "__name__", str(annotation).replace("typing.", ""))


def _default_name(default: object, factory: object | None, required: bool) -> str:
    if required:
        return "required"
    if factory is not None:
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"generated by {name}"
    if isinstance(default, Enum):
        return repr(default.value)
    return repr(default)


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _record_rows(record: type) -> list[tuple[str, str, str, str]]:
    if issubclass(record, Enum):
        return [(member.name, record.__name__, repr(member.value), "—") for member in record]

    if hasattr(record, "model_fields"):
        rows = []
        for name, info in record.model_fields.items():
            rows.append(
                (
                    name,
                    _type_name(info.annotation),
                    _default_name(info.default, info.default_factory, info.is_required()),
                    info.description or "—",
                )
            )
        return rows

    if is_dataclass(record):
        rows = []
        for info in fields(record):
            required = info.default is MISSING and info.default_factory is MISSING
            factory = None if info.default_factory is MISSING else info.default_factory
            default = None if info.default is MISSING else info.default
            rows.append(
                (
                    info.name,
                    _type_name(info.type),
                    _default_name(default, factory, required),
                    "—",
                )
            )
        return rows

    return []


def _record_table(name: str, locations: dict[str, tuple[str, str]]) -> list[str]:
    module_name, attribute = locations[name]
    record = getattr(import_module(module_name), attribute)
    rows = _record_rows(record)
    if not rows:
        return []

    show_descriptions = any(description != "—" for *_, description in rows)
    lines = (
        ["| Field | Type | Default | Description |", "| --- | --- | --- | --- |"]
        if show_descriptions
        else ["| Field | Type | Default |", "| --- | --- | --- |"]
    )
    for field_name, annotation, default, description in rows:
        cells = [
            f"`{_escape_cell(field_name)}`",
            f"`{_escape_cell(annotation)}`",
            f"`{_escape_cell(default)}`",
        ]
        if show_descriptions:
            cells.append(_escape_cell(description))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def _directive(name: str, locations: dict[str, tuple[str, str]]) -> list[str]:
    module, attribute = locations[name]
    lines = [f"::: {module}.{attribute}"]
    options: list[str] = []
    members = EXPLICIT_MEMBERS.get(name)
    if members:
        options.append("      members:")
        options.extend(f"        - {member}" for member in members)
    elif name in RECORDS or name in COMPATIBILITY_CLASSES:
        options.append("      members: false")
    if name in HIDDEN_SIGNATURES:
        options.append("      show_signature: false")
    if options:
        lines.append("    options:")
        lines.extend(options)
    lines.append("")
    return lines


def _render_page(page: ReferencePage, locations: dict[str, tuple[str, str]]) -> str:
    lines = [
        GENERATED,
        "",
        f"# {page.title}",
        "",
        f"**{page.tier}.** {page.introduction}",
        "",
    ]
    for name in page.names:
        lines.extend(_directive(name, locations))
        if name in RECORDS:
            lines.extend(_record_table(name, locations))
    return "\n".join(lines)


def _render_index() -> str:
    lines = [
        GENERATED,
        "",
        "# Python API",
        "",
        "Archetype has one compatibility surface with several levels of abstraction. "
        "Most applications only need the runtime, world-handle, and building-block pages.",
        "",
        "| Surface | Use it for |",
        "| --- | --- |",
    ]
    for page in PAGES:
        lines.append(f"| [{page.title}](python/{page.slug}.md) | {page.introduction} |")
    lines.extend(
        (
            "",
            "## Public API rule",
            "",
            "Names exported from `archetype` are supported compatibility contracts. "
            "Types exposed by their public signatures are part of that contract as well. "
            "Recommended APIs receive examples and prominent placement; advanced and "
            "compatibility APIs remain documented without being presented as the default.",
            "",
            "See [API stability and docstrings](../guide/api-stability.md) for the full policy.",
            "",
            "## Compatibility aliases",
            "",
        )
    )
    for alias, target in ALIASES.items():
        lines.append(f"- `{alias}` is an alias for `{target}`.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    locations = _validate_coverage()
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(_render_index(), encoding="utf-8", newline="\n")
    expected = set()
    for page in PAGES:
        destination = PAGES_DIR / f"{page.slug}.md"
        destination.write_text(_render_page(page, locations), encoding="utf-8", newline="\n")
        expected.add(destination)
    for stale in PAGES_DIR.glob("*.md"):
        if stale not in expected:
            stale.unlink()
    print(f"Generated {OUTPUT} and {len(PAGES)} Python API pages")


if __name__ == "__main__":
    main()
