#!/usr/bin/env python3
# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate the human-readable contract traceability view from its registry."""

from __future__ import annotations

import argparse
from pathlib import Path

from scripts.validate_contracts import REGISTRY, ROOT, load_contracts, validate_contracts

OUTPUT = ROOT / "docs" / "reference" / "contract-traceability.md"


def _source_link(source: str) -> str:
    path = Path(source)
    try:
        relative = path.relative_to("docs")
    except ValueError:
        return source
    return f"../{relative.as_posix()}"


def render(registry_path: Path = REGISTRY) -> str:
    rows = load_contracts(registry_path)
    lines = [
        "<!-- Generated by scripts/generate_contract_traceability.py; do not edit. -->",
        "",
        "# Contract traceability",
        "",
        "This index is generated from `quality/contracts.toml`. The TOML registry is the",
        "machine authority; this page is its review surface.",
        "",
        "| Contract | Owner | Risk | Normative source | Executable evidence | Profiles |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        source = str(row["source"])
        source_cell = f"[{source}]({_source_link(source)}) — {row['section']}"
        evidence = []
        for label, field in (
            ("pytest", "pytest"),
            ("static", "static"),
            ("eval", "evals"),
            ("benchmark", "benchmarks"),
        ):
            values = row.get(field, [])
            if values:
                evidence.append(f"{label}: {len(values)}")
        lines.append(
            "| `{id}` | `{owner}` | {risk} | {source} | {evidence} | {profiles} |".format(
                id=row["id"],
                owner=row["owner"],
                risk=row["risk"],
                source=source_cell,
                evidence="; ".join(evidence),
                profiles=", ".join(f"`{profile}`" for profile in row["profiles"]),
            )
        )
    lines.extend(
        [
            "",
            "Profile membership states where a contract must be enforced. Eval suite",
            "blocking/advisory policy is defined separately in `quality/eval_profiles.toml`;",
            "benchmark policy is defined in `quality/benchmarks.toml`.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    errors = validate_contracts(registry_path=args.registry)
    if errors:
        for error in errors:
            print(f"contract registry error: {error}")
        return 1

    expected = render(args.registry)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
        if actual != expected:
            print(
                f"Contract traceability is stale: run {Path(__file__).as_posix()} "
                f"--output {args.output.as_posix()}"
            )
            return 1
        print("Contract traceability is current")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
