#!/usr/bin/env python3
# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Generate the operator view of the pinned execution-environment inventory."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from archetype.app.sandboxes.versions import (
    PinnedArtifact,
    VersionInventory,
    load_version_inventory,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "version-inventory.md"


def _pin_row(artifact: PinnedArtifact) -> str:
    consumers = ", ".join(artifact.consumers)
    return (
        f"| `{artifact.artifact_id}` | {artifact.role} | {artifact.kind} | `{artifact.name}` "
        f"| `{artifact.version}` | `{artifact.immutable_ref}` | {consumers} |"
    )


def render(inventory: VersionInventory | None = None) -> str:
    inventory = inventory or load_version_inventory()
    pinned = [artifact for artifact in inventory.artifacts if artifact.status == "pinned"]
    planned = [artifact for artifact in inventory.artifacts if artifact.status == "planned"]
    lines = [
        "<!-- Generated by scripts/generate_version_inventory.py; do not edit. -->",
        "",
        "# Version inventory",
        "",
        "This page is generated from `src/archetype/app/sandboxes/versions.toml`, the",
        "machine-readable inventory of every executable dependency that can affect a",
        "coding-agent attempt. The TOML inventory is the machine authority; this page",
        "is its operator review surface. The normative contract, including the",
        "fail-closed resolution rules and the upgrade/rollback procedure, is",
        "[Sandbox execution, section 9](../guide/sandbox-execution.md).",
        "",
        f"Inventory content digest: `{inventory.digest}`",
        "",
        "## Pinned artifacts",
        "",
        "| Artifact | Role | Kind | Name | Version | Immutable reference | Consumers |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        *(_pin_row(artifact) for artifact in pinned),
        "",
        "## Planned artifacts",
        "",
        "Planned rows declare a pinning obligation whose concrete artifact is not",
        "selected yet. Resolving one fails closed until it is pinned.",
        "",
        "| Artifact | Role | Consumers |",
        "| --- | --- | --- |",
        *(
            f"| `{artifact.artifact_id}` | {artifact.role} | {', '.join(artifact.consumers)} |"
            for artifact in planned
        ),
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    expected = render()
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current != expected:
            print(
                f"{args.output} is stale; run scripts/generate_version_inventory.py",
                file=sys.stderr,
            )
            return 1
        print("Version inventory audit passed")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
