# Copyright 2026 Vangelis Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Actor-free application facade contract."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from archetype.app.models import Command


@runtime_checkable
class iRuntimeApplication(Protocol):
    """Complete trusted-host workflow surface implemented by RuntimeApplication."""

    async def stop_admission(self) -> None: ...
    async def create_entity(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create_entities(self, *args: Any, **kwargs: Any) -> Any: ...
    def reserve_entity_ids(self, *args: Any, **kwargs: Any) -> Any: ...
    async def spawn_with_reserved_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def remove_entity(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update_entity(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add_components(self, *args: Any, **kwargs: Any) -> Any: ...
    async def remove_components(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add_processor(self, *args: Any, **kwargs: Any) -> Any: ...
    async def remove_processor(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create_world(self, *args: Any, **kwargs: Any) -> Any: ...
    async def fork_world(self, *args: Any, **kwargs: Any) -> Any: ...
    async def destroy_world(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_world_info(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_worlds(self, *args: Any, **kwargs: Any) -> Any: ...
    async def discover_worlds(self, *args: Any, **kwargs: Any) -> Any: ...
    async def open_world_readonly(self, *args: Any, **kwargs: Any) -> Any: ...
    async def resume_world(self, *args: Any, **kwargs: Any) -> Any: ...
    async def step(self, *args: Any, **kwargs: Any) -> Any: ...
    async def run(self, *args: Any, **kwargs: Any) -> Any: ...
    async def run_episode(self, *args: Any, **kwargs: Any) -> Any: ...
    async def run_rollout(self, *args: Any, **kwargs: Any) -> Any: ...
    async def autoresearch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def query_components(self, *args: Any, **kwargs: Any) -> Any: ...
    async def query_archetype(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_signatures(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add_resource(self, *args: Any, **kwargs: Any) -> Any: ...
    async def add_hook(self, *args: Any, **kwargs: Any) -> Any: ...
    async def remove_hook(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_processors(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_hooks(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_resources(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_audit_history(self, *args: Any, **kwargs: Any) -> Any: ...
    async def ingest_artifact(self, *args: Any, **kwargs: Any) -> Any: ...
    async def ingest_files(self, *args: Any, **kwargs: Any) -> Any: ...
    async def write_artifacts(self, *args: Any, **kwargs: Any) -> Any: ...
    async def query_artifacts(self, *args: Any, **kwargs: Any) -> Any: ...
    async def run_graders(self, *args: Any, **kwargs: Any) -> Any: ...
    async def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...
    def require_world(self, world_id: Any) -> None: ...
    def validate_deferred_command(self, command: Command) -> None: ...
    async def submit(self, *args: Any, **kwargs: Any) -> Any: ...
    async def submit_batch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def submit_spawn(self, *args: Any, **kwargs: Any) -> Any: ...
    async def drain_and_apply(self, *args: Any, **kwargs: Any) -> Any: ...
